#DOCKER-VERSION 0.9.1
#
#VERSION 0.4
#
# monoxide mono-devel package on Ubuntu 13.10

MAINTAINER Wayne Douglas <wayne@made-software.com>
FROM    base

EXPOSE 4200

USER 	root
CMD 	["/home/sonatribe/setup/docker/ui/entrypoint.sh"]
