#DOCKER-VERSION 0.9.1
#
#VERSION 0.1
#
# monoxide mono-devel package on Ubuntu 13.10

FROM    ubuntu

MAINTAINER Wayne Douglas <wayne@made-software.com>

RUN 	  git clone https://wayne-o:William2014@bitbucket.org/sonatribe/sonatribe /home/sonatribe
WORKDIR   /home/sonatribe/sonatribe-ui
